/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

type AWSMobileConfig = {
    aws_project_region: string;
    aws_appsync_graphqlEndpoint: string;
    aws_appsync_region: string;
    aws_appsync_authenticationType: 'API_KEY' | 'AWS_IAM' | 'OPENID_CONNECT' | 'AMAZON_COGNITO_USER_POOLS';
    aws_appsync_apiKey: string;
};

const awsmobile: AWSMobileConfig = {
    aws_project_region: "ap-southeast-1",
    aws_appsync_graphqlEndpoint: "https://graalphdvbb67lt6efpwtttkry.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    aws_appsync_region: "ap-southeast-1",
    aws_appsync_authenticationType: "API_KEY",
    aws_appsync_apiKey: "da2-fg7s4l5n3vghtncm26gvo7jdvy"
};

export default awsmobile;

